apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: c6m8l1ywe-python-gitops
  description: This is GitOps manifest for c6m8l1ywe-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=c6m8l1ywe-python
    backstage.io/kubernetes-id: c6m8l1ywe-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: c6m8l1ywe-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:c6m8l1ywe-python
