apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c6m8l1ywe-python
  janus-idp.io/tekton: c6m8l1ywe-python
  backstage.io/kubernetes-id: c6m8l1ywe-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c6m8l1ywe-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
