apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c6m8l1ywe-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c6m8l1ywe-python 
  name: c6m8l1ywe-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c6m8l1ywe-python 
